version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
    image: nginx-tls-alpine
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env_nginx
    volumes:
      - www-data:/domains/${DOMAIN_NAME}/public_html
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb/.
    image: mariadb-alpine
    networks:
      - inception
    env_file:
      - .env_mariadb
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress/.
    image: wordpress-alpine
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env_wordpress
    volumes:
      - www-data:/domains/${DOMAIN_NAME}/public_html
    restart: always

volumes:
  www-data:
    driver_opts:
      type: none
      device: ${PWD}/srcs/volumes/wp
      o: bind