version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx-tls-alpine
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb/.
      # args:
      #   - DOMAIN_NAME=${DOMAIN_NAME}
    image: mariadb-alpine
    networks:
      - inception
    restart: always