version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
    image: nginx-tls-alpine
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env_nginx
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb/.
    image: mariadb-alpine
    networks:
      - inception
    env_file:
      - .env_mariadb
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress/.
    image: wordpress-alpine
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env_wordpress
    restart: always